### ISSUE TITLE
Standalone any bit Bug - NULL pointer dereference in ResourceManager::vLoadFile_StateMachine_464A70()

### ISSUE THREAD

**Issue by neuromancer** [AliveTeam/alive_reversing#361]
I compiled the latest revision (36c46d5287d4dd4a9cb5cbb483e526da22c813c1) in ArchLinux. Then, run it with the GOG release: 

```
$ gdb --args /tmp/alive_reversing/build/Source/AliveExe/AliveExe 
...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
2020-03-31 21:57:59,804 WARNING [default] BaseAnimatedWithPhysicsGameObject::BaseAnimatedWithPhysicsGameObject() [W] Exists only to make things build - func may break behaviour of objects
2020-03-31 21:57:59,805 INFO [default] int WinMain_4EE631(HINSTANCE, HINSTANCE, LPSTR, int) [I] Main enter
2020-03-31 21:57:59,806 WARNING [default] int PSX_CD_Add_EMU_Path_4FAC00(const char*) [W] Not implemented
2020-03-31 21:58:00,092 WARNING [default] void PSX_EMU_Set_screen_mode_4F9420(char) [W] Not implemented
2020-03-31 21:58:00,092 INFO [default] int VGA_FullScreenSet_4F31F0(bool) [I] Stub
2020-03-31 21:58:00,203 WARNING [default] void VLC_Tables_Init_496720() [W] Not implemented
2020-03-31 21:58:00,204 WARNING [default] void sub_4FBA20() [W] Not implemented
2020-03-31 21:58:00,204 WARNING [default] void CheckShiftCapslock_4953B0() [W] Not implemented
2020-03-31 21:58:00,204 WARNING [default] void Draw_Debug_Strings_4F2800() [W] Not implemented
[New Thread 0x7ffff48e7700 (LWP 20049)]
2020-03-31 21:58:00,232 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] SDL Audio Driver 0 pulseaudio
2020-03-31 21:58:00,232 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] SDL Audio Driver 1 alsa
2020-03-31 21:58:00,232 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] SDL Audio Driver 2 dsp
2020-03-31 21:58:00,232 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] SDL Audio Driver 3 jack
2020-03-31 21:58:00,233 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] SDL Audio Driver 4 disk
2020-03-31 21:58:00,233 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] SDL Audio Driver 5 dummy
[New Thread 0x7fffe3d11700 (LWP 20051)]
2020-03-31 21:58:01,774 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] -----------------------------
2020-03-31 21:58:01,774 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] Audio Device opened, got specs:
2020-03-31 21:58:01,774 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] Channels: 2 nFormat: 32784 nFreq: 44100 nPadding: 0 nSamples: 2048 nSize: 8192 nSilence: 0
2020-03-31 21:58:01,774 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] Driver: pulseaudio
2020-03-31 21:58:01,774 INFO [default] void SDLSoundSystem::Init(unsigned int, int, int) [I] -----------------------------
[New Thread 0x7fffe3510700 (LWP 20052)]

Thread 1 "AliveExe" received signal SIGSEGV, Segmentation fault.
0x00005555557e1899 in ResourceManager::vLoadFile_StateMachine_464A70() ()
(gdb) bt
#0  0x00005555557e1899 in ResourceManager::vLoadFile_StateMachine_464A70() ()
#1  0x00005555557e2afc in ResourceManager::VUpdate() ()
#2  0x00005555557e278d in ResourceManager::LoadingLoop_465590(short) ()
#3  0x00005555557e3296 in ResourceManager::LoadResourceFile_49C170(char const*, Camera*) ()
#4  0x00005555557ce3e8 in Game_Run_466D40() ()
#5  0x00005555557ce8f9 in Game_Main_4949F0() ()
#6  0x000055555579fc89 in WinMain_4EE631(void*, void*, char*, int) ()
#7  0x000055555579f8f6 in main ()
(gdb) x/i $rip
=> 0x5555557e1899 <_ZN15ResourceManager29vLoadFile_StateMachine_464A70Ev+157>:	mov    0x10(%rax),%edx
(gdb) info registers 
rax            0x0                 0
rbx            0x5555562275d0      93825005680080
rcx            0x7ffff7a5d4c0      140737348228288
rdx            0x73                115
rsi            0x555555a2e170      93824997319024
rdi            0x555556f1b079      93825019261049
rbp            0x7fffffffe400      0x7fffffffe400
rsp            0x7fffffffe3e0      0x7fffffffe3e0
r8             0x0                 0
r9             0x9                 9
r10            0xfffffffffffff099  -3943
r11            0x0                 0
r12            0x55555579f7c0      93824994637760
r13            0x7fffffffe6e0      140737488348896
r14            0x0                 0
r15            0x0                 0
rip            0x5555557e1899      0x5555557e1899 <ResourceManager::vLoadFile_StateMachine_464A70()+157>
eflags         0x210246            [ PF ZF IF RF ID ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```

**Comment by paulsapps** [comment]
can this be easily reproduced?

**Comment by paulsapps** [comment]
(btw this can happen if the working dir is incorrect and the game can't find the files, that is more of an OG bug in the fact it just dies when game data isn't found)

**Comment by neuromancer** [comment]
It seems easy to reproduce. I wonder if it is an issue with case-sensitive files in Linux (which is not the case in Windows). This is the list of files from the GOG version of the game:

```
ABEMORPH.ddv  d2p6p10.ddv   F2P5P8.ddv                 logs
AbeWin.exe    d2p7p10b.ddv  F2P6P8B.ddv                LP1C15C3.ddv
Badend.ddv    d2p7p10.ddv   F2P6P8.ddv                 LP1C16C3.ddv
Barrels.ddv   d2p8p10b.ddv  F2P7P8B.ddv                LP1C3C15.ddv
Begin.ddv     d2p8p10.ddv   F2P7P8.ddv                 LP1C3C16.ddv
c1.lvl        d2p9p10b.ddv  F2P8F4.ddv                 LP5C3C4.ddv
d1.lvl        d2p9p10.ddv   F2P8P2.ddv                 LP5C4C3.ddv
d1p1p2.ddv    d7c11c12.ddv  f2p8p3.ddv                 manual.pdf
D1P2P1.ddv    d7c12c11.ddv  F2P8P4.ddv                 Mollock.ddv
d1p3p4.ddv    d7.lvl        F2P8P5.ddv                 moon.ddv
D1P4P3.ddv    Drag.ddv      F2P8P6.ddv                 PARAMITE.ddv
d1p6p7.ddv    e1.lvl        F2P8P7.ddv                 PARSCAR.ddv
D1P7P6.ddv    E1P4C8.ddv    F4C11C13.ddv               r1.lvl
d1p9d2.ddv    e2.lvl        F4C13C11.ddv               R1P11P6.ddv
d2.lvl        E2P2R2.ddv    f4.lvl                     r1p13p14.ddv
d2p10d7.ddv   f1.lvl        GAMEBGN.ddv                R1p13p1.ddv
d2p10p2.ddv   F1p1p2.ddv    goggame-1207658705.hashdb  r1p14p13.ddv
d2p10p3.ddv   F1P2P1.ddv    goggame-1207658705.ico     R1P18P19.ddv
d2p10p4.ddv   F1P2P5.ddv    goggame-1207658705.info    R1p18p1.ddv
d2p10p5.ddv   F1P5P2.ddv    Goodend.ddv                R1P19P18.ddv
d2p10p6.ddv   F1P5P6.ddv    gtddlogo.ddv               R1P1P13.ddv
d2p10p7.ddv   F1P6P5.ddv    Halts.ddv                  R1p1p18.ddv
d2p10p8.ddv   F1P8P9.ddv    l1.lvl                     R1P6P11.ddv
d2p10p9.ddv   F1p9f2.ddv    L1P1C14.ddv                r2.lvl
d2p1p10.ddv   F1P9P8.ddv    L1P1P2.ddv                 r6.lvl
d2p2p10b.ddv  f2.lvl        L1P2P1.ddv                 README.TXT
d2p2p10.ddv   F2P1P8.ddv    L1P2P3.ddv                 s1.lvl
d2p3p10b.ddv  F2P2P8B.ddv   L1P3P2.ddv                 Scrab.ddv
d2p3p10.ddv   F2P2P8.ddv    L1P5C4.ddv                 scriptinterpreter.exe
d2p4p10b.ddv  F2p3p8b.ddv   L1P5P6.ddv                 ScrScar.ddv
d2p4p10.ddv   F2p3p8.ddv    L1P6E2.ddv                 webcache.zip
d2p5p10b.ddv  F2P4P8B.ddv   L1P6P5.ddv                 xaosopen.ddv
d2p5p10.ddv   F2P4P8.ddv    li1p6e2.ddv
d2p6p10b.ddv  F2P5P8B.ddv   logoint.ddv
```

**Comment by paulsapps** [comment]
That appears to be Abe's Oddysee data, so that would explain it :)

**Comment by neuromancer** [comment]
Oh, sorry, this is my fault.

**Comment by paulsapps** [comment]
haha - well probably something should be done rather than just exploding while critical files are missing
